import type { NextPage } from "next";
import Head from "next/head";
import Navigation from "../components/Navigation";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <main className={styles.main}>
        <h1>Accessing Environment Variables</h1>
        <h2>On Client</h2>
        <h3>in Next.js</h3>
      </main>
    </div>
  );
};

export default Home;
