import type { NextPage } from "next";
import Head from "next/head";
import Navigation from "../components/Navigation";
import { Stringify } from "../components/Stringify";
import styles from "../styles/Home.module.css";

const Third: NextPage = (props: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <main className={styles.main}>
        <Stringify title="third page data" data={props} />
      </main>
    </div>
  );
};

export default Third;
